version: 2
plugins:
  duplication:
    enabled: true
    config:
      languages:
        javascript:
          mass_threshold: 50

  # TODO: errors
  fixme:
    enabled: false

exclude_patterns:
- '**/english.ts'
- '**/benchmarks/'
- '**/ember-cli-build.js'
- 'benchmarks/'
- 'client/android-wrapper/'
- 'relays/'
- 'client/web/emberclear/config/'
- 'client/web/emberclear/tests/'
- 'client/web/emberclear/vendor/'
- 'client/web/emberclear/dist/'
- 'client/web/emberclear/types/'
- '**/node_modules/'
- '**/dist/'
- '**/tests/'
- '**/config/'
- '**/script/'
- '**/vendor/'
- '**/*.d.ts'
