codecov:
  require_ci_to_pass: yes

coverage:
  precision: 4
  round: down
  range: "50...100"

  status:
    project: yes
    patch: yes
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no

ignore:
  - "images/**/*"
  - "scripts/**/*"
  - ".netlify/**/*"
  - ".github/**/*"
  - "packages/android-wrapper/**/*"
  - "packages/benchmarks/**/*"
  - "packages/relays/**/*"
  - "packages/smoke-tests/**/*"

fixes:
  - "::packages/frontend/"
