#!/bin/bash

GITHUB_URL="https://github.com"
GITHUB_API_URL="https://api.github.com"

DEPLOYMENT_ID=$1
DEPLOY_STATE=$2
DESCRIPTION=$3

echo "Setting status to ${DEPLOY_STATE} for deployment-id '${DEPLOYMENT_ID}'"
curl --silent --show-error --fail \
    -X POST "${GITHUB_API_URL}/repos/${GITHUB_REPOSITORY}/deployments/${DEPLOYMENT_ID}/statuses" \
    -H "Authorization: token ${GITHUB_TOKEN}" \
    -H "Content-Type: text/json; charset=utf-8" \
    -H "Accept: application/vnd.github.flash-preview+json" \
    -d @- <<EOF
{
    "state": "${DEPLOY_STATE}",
    "target_url": "${GITHUB_URL}/${GITHUB_REPOSITORY}/actions",
    "description": "${DESCRIPTION}"
}
EOF
