#!/bin/bash
# https://stackoverflow.com/questions/6059336/how-to-find-the-current-git-branch-in-detached-head-state

BRANCH=$(\
  git for-each-ref \
  --format='%(objectname) %(refname:short)' refs/heads \
  | awk "/^$(git rev-parse HEAD)/ {print \$2}"\
)

echo "Current branch: $BRANCH"

if [[ "$BRANCH" == "master" ]]; then
  echo "Current branch is master. Starting deploy..."

  NETLIFY_CLI_VERSION=0.4.0

  # exit if any of the following errors
  set -e

  ( cd ./packages/frontend && rm -rf dist tmp )
  time ./run yarn build:production
  
  ( ./scripts/publish )
else
  echo "current branch ($BRANCH) did not equal 'master'."
fi
