#!/bin/bash
BRANCH=$(git rev-parse --abbrev-ref HEAD)

echo "Current branch: $BRANCH"

if [[ "$BRANCH" == "master" ]]; then
  echo "Current branch is master. Starting deploy..."

  time ./run yarn build:production

  wget https://github.com/netlify/netlifyctl/releases/download/v$NETLIFY_CLI_VERSION/netlifyctl-linux-amd64-$NETLIFY_CLI_VERSION.tar.gz
  tar -xf netlifyctl-linux-amd64-$NETLIFY_CLI_VERSION.tar.gz

  ./netlifyctl -y deploy --site-id $NETLIFY_SITE_ID --access-token $NETLIFY_ACCESS_TOKEN --publish-directory ./packages/frontend/dist

  deploy_status=$?
  echo "Deploy finished with status: $deploy_status"

  deploy_status
fi
