#!/bin/bash
cd packages/frontend/

GIT_TAG=$CI_COMMIT_SHA
REPO_NAME="nullvoxpopuli/emberclear"
GIT_IMAGE="$REPO_NAME:$GIT_TAG"

docker build -t "$REPO_NAME" -f Dockerfile.release .

echo "$DOCKERHUB_PASSWORD" | docker login --username $DOCKERHUB_USER --password-stdin

docker tag "$REPO_NAME" "$REPO_NAME:latest"
docker tag "$REPO_NAME" "$GIT_IMAGE"

docker push $GIT_IMAGE
docker push "$REPO_NAME:latest"

deploy_status=$?
echo "Deploy finished with status: $deploy_status"

exit $deploy_status
