#!/bin/bash
cp ./scripts/_redirects packages/frontend/dist

wget https://github.com/netlify/netlifyctl/releases/download/v$NETLIFY_CLI_VERSION/netlifyctl-linux-amd64-$NETLIFY_CLI_VERSION.tar.gz
tar -xf netlifyctl-linux-amd64-$NETLIFY_CLI_VERSION.tar.gz

# don't exit if a script errors, because we want custom logging
set +e

./netlifyctl -y deploy --site-id $NETLIFY_SITE_ID --access-token $NETLIFY_ACCESS_TOKEN --publish-directory ./packages/frontend/dist

deploy_status=$?
echo "Deploy finished with status: $deploy_status"

exit $deploy_status