name: Frontend Deploy Preview
on:
  pull_request:
    branches: [master]
    # paths:
    #   - 'packages/frontend/*'
jobs:
  deploy:
    name: Deploy a preview to Netlify
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - uses: unacast/actions/github-deploy@master
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - name: Notify GitHub Deploy Is Starting

    - name: Install
      run: |
        # apt-get install -y jq
        curl https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64
        npm install -g netlify-cli
        ./run yarn install

    - name: Build
      run: ./run yarn build:production

    - name: Deploy a preview to Netlify
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_ACCESS_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      run: |

        DEPLOY_ID=$(./scripts/github/create-deploy | ./jq-linux64 '.id')

        ./scripts/github/update-deploy-state $DEPLOY_ID in_progress

        DEPLOY_URL=$(netlify deploy --dir=packages/frontend/dist --json | ./jq-linux64 '.deploy_url')

        echo ""
        echo "Deploy Preview URL:"
        echo $DEPLOY_URL
        echo ""

        ./scripts/github/update-deploy-state $DEPLOY_ID success $DEPLOY_URL

