name: 'Web @emberclear/ui'
on:
  pull_request:
    branches: [master]
    paths:
    - 'client/web/addons/ui/**'
    - 'client/web/package.json'

env:
  root: client/web/
  addon: addons/ui/
  full: client/web/addons/ui/

jobs:
  lint:
    name: 'Lint'
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v2
    - uses: volta-cli/action@v1

    - name: Install
      working-directory: ${{ env.root }}
      run: yarn install

    - name: "JS/TS"
      working-directory: ${{ env.root }}
      run: yarn eslint ${{ env.addon }} --ext js,ts

    - name: "Templates"
      working-directory: ${{ env.full }}
      run: yarn ember-template-lint .

    - name: "Styles"
      working-directory: ${{ env.root }}
      run: yarn stylelint ${{ env.addon }}**/*.css

    - name: 'Type Correctness'
      working-directory: ${{ env.full }}
      run: yarn tsc --build

  test:
    name: 'Test'
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v2
    - uses: volta-cli/action@v1

    - name: Install
      working-directory: ${{ env.root }}
      run: yarn install

    - name: Ember
      working-directory: "${{ env.root }}/${{ env.addon }}"
      run: yarn test





